// GENERATED — 由 `dart run ffigen --config ffigen_xrslam.yaml` 生成,请勿手改。
//
// ⚠️ ABI 契约提醒(改头文件时必须同步想清楚):
//   • XRSLAMImage / XRSLAMHealth 等是 **caller-allocates** 结构体,
//     追加字段会改 sizeof。Dart 侧用 calloc 天然清零,是最安全的一侧;
//     但**旧头编译的原生调用方配新库**没有自描述前缀可救,只能同版本发布。
//   • 出参契约:非 NULL 时库会**无条件先清零**,所以拿到错误码时出参也是已定义的。
//   • 双调用惯用法:出参传 NULL 时返回所需容量;容量不足返回 XRSLAM_INCOMPLETE。
//   • ⚠️ XRSLAMCreate 是上游遗留约定 **1=成功 / 0=失败**,与其余 API 的
//     0=OK / 负数=错误 **正好相反**。封装层必须用统一的 check 辅助函数。
// ignore_for_file: always_specify_types, camel_case_types, non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// XRSLAM C ABI (OpenXRLab / RD-VIO),pocketworld fork。
/// ⚠️ 生成物不要手改 —— 头文件变了就重新生成。
///
class XrslamBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  XrslamBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  XrslamBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  /// @brief create SLAM system with configuration files.
  /// @param[in] slam_config_path slam configuration file path.
  /// @param[in] device_config_path  device configuration file path, include camera
  /// intrinsics, extrinsics and so on.
  /// @param[in] license_path  license path
  /// @param[in] product_name  product name which user can define
  /// @param[out] config configuration of slam and device
  /// @return 1 success, otherwise 0
  int XRSLAMCreate(
    ffi.Pointer<ffi.Char> slam_config_path,
    ffi.Pointer<ffi.Char> device_config_path,
    ffi.Pointer<ffi.Char> license_path,
    ffi.Pointer<ffi.Char> product_name,
    ffi.Pointer<ffi.Pointer<ffi.Void>> config,
  ) {
    return _XRSLAMCreate(
      slam_config_path,
      device_config_path,
      license_path,
      product_name,
      config,
    );
  }

  late final _XRSLAMCreatePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Void>>,
          )
        >
      >('XRSLAMCreate');
  late final _XRSLAMCreate =
      _XRSLAMCreatePtr.asFunction<
        int Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Pointer<ffi.Void>>,
        )
      >();

  /// @brief push sensor data to SLAM system
  /// @param[in] sensor_type sensor type.
  /// @param[in] sensor_data sensor data.
  void XRSLAMPushSensorData(
    XRSLAMSensorType sensor_type,
    ffi.Pointer<ffi.Void> sensor_data,
  ) {
    return _XRSLAMPushSensorData(sensor_type.value, sensor_data);
  }

  late final _XRSLAMPushSensorDataPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.UnsignedInt, ffi.Pointer<ffi.Void>)
        >
      >('XRSLAMPushSensorData');
  late final _XRSLAMPushSensorData =
      _XRSLAMPushSensorDataPtr.asFunction<
        void Function(int, ffi.Pointer<ffi.Void>)
      >();

  /// @brief [pw] 同 XRSLAMPushSensorData,但返回错误码而不是在出错时终止进程。
  /// @return XRSLAM_OK 或 XRSLAM_ERR_*
  /// @warning 丢帧对 VIO 是危险的(会变成难查的位姿漂移),调用方必须至少对
  /// 非 OK 的返回做计数打点,不要静默忽略。
  int XRSLAMPushSensorDataChecked(
    XRSLAMSensorType sensor_type,
    ffi.Pointer<ffi.Void> sensor_data,
  ) {
    return _XRSLAMPushSensorDataChecked(sensor_type.value, sensor_data);
  }

  late final _XRSLAMPushSensorDataCheckedPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.UnsignedInt, ffi.Pointer<ffi.Void>)
        >
      >('XRSLAMPushSensorDataChecked');
  late final _XRSLAMPushSensorDataChecked =
      _XRSLAMPushSensorDataCheckedPtr.asFunction<
        int Function(int, ffi.Pointer<ffi.Void>)
      >();

  /// @brief end one frame input and run slam
  void XRSLAMRunOneFrame() {
    return _XRSLAMRunOneFrame();
  }

  late final _XRSLAMRunOneFramePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>('XRSLAMRunOneFrame');
  late final _XRSLAMRunOneFrame =
      _XRSLAMRunOneFramePtr.asFunction<void Function()>();

  /// @brief get SLAM results (遗留入口,仅供仓库内 C++ 使用)
  /// @param[in]  result_type slam result type.
  /// @param[out] result_data result data.
  /// @warning [pw] 第二参是裸 void*,传错枚举=可精确构造的越界写(例如给
  /// XRSLAM_RESULT_CAMERA_POSE 传一个 16 字节的结构体,库会写 64 字节)。
  /// Dart 侧类型系统对此零保护 ⇒ **必须在 ffigen 的 functions.exclude
  /// 里挡掉本函数**,只用下面的类型化 XRSLAMGet* 接口。
  /// @note    XRSLAM_RESULT_LANDMARKS 分支已删除(改用 XRSLAMGetLandmarks);
  /// XRSLAM_RESULT_DEBUG_LOGS 从来没有实现,落到空 break。
  void XRSLAMGetResult(
    XRSLAMResultType result_type,
    ffi.Pointer<ffi.Void> result_data,
  ) {
    return _XRSLAMGetResult(result_type.value, result_data);
  }

  late final _XRSLAMGetResultPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.UnsignedInt, ffi.Pointer<ffi.Void>)
        >
      >('XRSLAMGetResult');
  late final _XRSLAMGetResult =
      _XRSLAMGetResultPtr.asFunction<
        void Function(int, ffi.Pointer<ffi.Void>)
      >();

  /// @warning [pw] 这两个函数在跟踪器尚未初始化时返回 **XRSLAM_OK 但 quaternion
  /// 全为 0** —— 零四元数不是旋转。根因在 detail.cpp:predict_pose 的
  /// else 分支(`output_pose.q.coeffs().setZero()`),而 track_camera 照样
  /// 把它存进 latest_pose_。返回码保持 XRSLAM_OK 是为了不改动既有仓内
  /// 调用方的行为;**新代码请改用 XRSLAMTryGetLatestPose**(已替你挡掉),
  /// 或读 XRSLAMHealth.latest_pose_degenerate。
  int XRSLAMGetBodyPose(ffi.Pointer<XRSLAMPose> out) {
    return _XRSLAMGetBodyPose(out);
  }

  late final _XRSLAMGetBodyPosePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<XRSLAMPose>)>>(
        'XRSLAMGetBodyPose',
      );
  late final _XRSLAMGetBodyPose =
      _XRSLAMGetBodyPosePtr.asFunction<int Function(ffi.Pointer<XRSLAMPose>)>();

  int XRSLAMGetCameraPose(ffi.Pointer<XRSLAMPose> out) {
    return _XRSLAMGetCameraPose(out);
  }

  late final _XRSLAMGetCameraPosePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<XRSLAMPose>)>>(
        'XRSLAMGetCameraPose',
      );
  late final _XRSLAMGetCameraPose =
      _XRSLAMGetCameraPosePtr.asFunction<
        int Function(ffi.Pointer<XRSLAMPose>)
      >();

  int XRSLAMGetState(ffi.Pointer<ffi.UnsignedInt> out) {
    return _XRSLAMGetState(out);
  }

  late final _XRSLAMGetStatePtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.UnsignedInt>)>
      >('XRSLAMGetState');
  late final _XRSLAMGetState =
      _XRSLAMGetStatePtr.asFunction<
        int Function(ffi.Pointer<ffi.UnsignedInt>)
      >();

  int XRSLAMGetBias(ffi.Pointer<XRSLAMIMUBias> out) {
    return _XRSLAMGetBias(out);
  }

  late final _XRSLAMGetBiasPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<XRSLAMIMUBias>)>>(
        'XRSLAMGetBias',
      );
  late final _XRSLAMGetBias =
      _XRSLAMGetBiasPtr.asFunction<int Function(ffi.Pointer<XRSLAMIMUBias>)>();

  int XRSLAMGetIntrinsics(ffi.Pointer<XRSLAMIntrinsics> out) {
    return _XRSLAMGetIntrinsics(out);
  }

  late final _XRSLAMGetIntrinsicsPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Pointer<XRSLAMIntrinsics>)>
      >('XRSLAMGetIntrinsics');
  late final _XRSLAMGetIntrinsics =
      _XRSLAMGetIntrinsicsPtr.asFunction<
        int Function(ffi.Pointer<XRSLAMIntrinsics>)
      >();

  /// @brief 版本串,caller-allocates。
  /// @param[out]    out_buf  接收缓冲;为 NULL 时只查长度。
  /// @param[in,out] io_len   入:out_buf 容量(字节,含结尾 '\0');
  /// 出:实际写入的字符数(不含结尾 '\0')。
  /// out_buf 为 NULL 时,出=所需字符数(不含 '\0')。
  /// @return XRSLAM_OK / XRSLAM_INCOMPLETE(已截断) / XRSLAM_ERR_BAD_ARG
  int XRSLAMGetVersion(
    ffi.Pointer<ffi.Char> out_buf,
    ffi.Pointer<ffi.Int32> io_len,
  ) {
    return _XRSLAMGetVersion(out_buf, io_len);
  }

  late final _XRSLAMGetVersionPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Int32>)
        >
      >('XRSLAMGetVersion');
  late final _XRSLAMGetVersion =
      _XRSLAMGetVersionPtr.asFunction<
        int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Int32>)
      >();

  /// @brief 取当前滑窗 3D landmarks(caller-allocates,两段式,库内零分配)。
  ///
  /// 内存 100% 归调用方,本函数不 new 也不 free —— 因此不需要、也不存在配套的
  /// Free 函数。取代已删除的 XRSLAM_RESULT_LANDMARKS + XRSLAMLandmarks。
  ///
  /// @param[out]    out_xyz         接收缓冲,布局是扁平的 [x0,y0,z0, x1,y1,z1, ...],
  /// 即需要 3 * point_count 个 double。
  /// 为 NULL 时只查数量,忽略 *io_point_count 的入值。
  /// @param[in,out] io_point_count  入:out_xyz 能装下的**点数**(不是字节数,
  /// 也不是 double 个数);出:实际写入的点数。
  /// out_xyz 为 NULL 时,出=当前可用点数。
  /// 本参数在**任何**返回路径上都被无条件写入。
  /// @return XRSLAM_OK            全部可用点已写入(或查询成功)
  /// XRSLAM_INCOMPLETE    容量不足,已写满 cap 个点,数据被截断
  /// XRSLAM_ERR_BAD_ARG   io_point_count 为 NULL,或 out_xyz 非 NULL 且容量为负
  /// XRSLAM_ERR_NOT_CREATED  SLAM 未创建 / 已销毁
  /// XRSLAM_ERR_UNAVAILABLE  本次构建关掉了 XRSLAM_ENABLE_DEBUG_INSPECTION,
  /// landmark 通道被编译掉(不是"当前没有点")
  ///
  /// @note 跟踪失败(XRSLAM_STATE_TRACKING_FAIL)时返回 0 个点,而不是上一帧的
  /// 陈旧点云 —— 内部那个 std::any 槽位是进程级的,不主动抑制就会渲染幽灵点。
  /// @note 两次调用之间点数可能变化,所以永远以第二次调用写回的实际点数为准,
  /// 不要拿查询结果当长度去遍历。
  /// @note 本函数与 XRSLAMGetCameraPose 走的是两把不同的锁、两次独立调用,
  /// **不保证同一帧**。AR 叠加对此敏感的话,只在跟踪稳定时取一次并缓存。
  ///
  /// @note [pw] ★ 已加过滤(条目 05)★ 本函数只交出**三分量 isfinite 且
  /// triangulated 为真**的点。上游发布循环只判 TT_VALID,于是两类垃圾点会混进来:
  /// - LandmarkState() 构造时 inv_depth = 0,而
  /// get_landmark_point() = bearing / inv_depth ⇒ IEEE754 除零 ⇒ ±Inf;
  /// - refine_window 的 else 分支对未三角化 track 设 inv_depth = -1.0 却
  /// **不清 TT_VALID** ⇒ 有限、但落在相机背后的垃圾点。
  /// 被丢掉的数量不会静默消失:用 XRSLAMGetLandmarksEx 的 out_stats,
  /// 或读 XRSLAMHealth.landmarks_rejected_*。
  int XRSLAMGetLandmarks(
    ffi.Pointer<ffi.Double> out_xyz,
    ffi.Pointer<ffi.Int32> io_point_count,
  ) {
    return _XRSLAMGetLandmarks(out_xyz, io_point_count);
  }

  late final _XRSLAMGetLandmarksPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Double>, ffi.Pointer<ffi.Int32>)
        >
      >('XRSLAMGetLandmarks');
  late final _XRSLAMGetLandmarks =
      _XRSLAMGetLandmarksPtr.asFunction<
        int Function(ffi.Pointer<ffi.Double>, ffi.Pointer<ffi.Int32>)
      >();

  /// @brief 带 triangulated 标志与过滤计账的 landmark 取数(条目 05)。
  ///
  /// 与 XRSLAMGetLandmarks 的唯一差别:
  /// - **不**过滤 untriangulated —— 交出所有 isfinite 的点,是否采用由调用方按
  /// out_flags 决定(±Inf/NaN 点永远丢弃,它们对任何用途都是垃圾)。
  /// - 额外交出并列的 uint8 标志数组与一份过滤计账。
  /// out_xyz 的扁平 [x0,y0,z0,x1,...] 布局**一个字节都没动**,dart:ffi 的
  /// asTypedList 零拷贝照旧;out_flags 是**并列的第二块缓冲**,不是交错。
  ///
  /// @param[out]    out_xyz         同 XRSLAMGetLandmarks;NULL 时只查数量。
  /// @param[out]    out_flags       可选,长度 >= 写入点数的 uint8 数组,
  /// bit0 = XRSLAM_LANDMARK_FLAG_TRIANGULATED。
  /// 只有 out_xyz 非 NULL 时才允许非 NULL,
  /// 否则返回 XRSLAM_ERR_BAD_ARG。
  /// @param[in,out] io_point_count  同 XRSLAMGetLandmarks,任何路径上都被写入。
  /// @param[out]    out_stats       可选。非 NULL 时**无条件先清零**,再填计账。
  /// @return 同 XRSLAMGetLandmarks 的那套码。
  int XRSLAMGetLandmarksEx(
    ffi.Pointer<ffi.Double> out_xyz,
    ffi.Pointer<ffi.UnsignedChar> out_flags,
    ffi.Pointer<ffi.Int32> io_point_count,
    ffi.Pointer<XRSLAMLandmarkStats> out_stats,
  ) {
    return _XRSLAMGetLandmarksEx(out_xyz, out_flags, io_point_count, out_stats);
  }

  late final _XRSLAMGetLandmarksExPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Double>,
            ffi.Pointer<ffi.UnsignedChar>,
            ffi.Pointer<ffi.Int32>,
            ffi.Pointer<XRSLAMLandmarkStats>,
          )
        >
      >('XRSLAMGetLandmarksEx');
  late final _XRSLAMGetLandmarksEx =
      _XRSLAMGetLandmarksExPtr.asFunction<
        int Function(
          ffi.Pointer<ffi.Double>,
          ffi.Pointer<ffi.UnsignedChar>,
          ffi.Pointer<ffi.Int32>,
          ffi.Pointer<XRSLAMLandmarkStats>,
        )
      >();

  /// @brief 读健康快照(条目 16 + Blocker 01 的诊断出口)。
  /// @param[out] out 非 NULL;**无条件先整体清零**,然后才可能被填。
  /// @return XRSLAM_OK / XRSLAM_ERR_BAD_ARG(out == NULL)。
  /// 未 Create 时**也返回 XRSLAM_OK**,out->overall == XRSLAM_HEALTH_NOT_CREATED,
  /// 这样"库没起来"和"调用姿势不对"能被区分开。
  /// @note 会做一次 O(点数) 的 landmark 扫描以填 landmarks_*,不要每帧调很多次。
  int XRSLAMGetHealth(ffi.Pointer<XRSLAMHealth> out) {
    return _XRSLAMGetHealth(out);
  }

  late final _XRSLAMGetHealthPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<XRSLAMHealth>)>>(
        'XRSLAMGetHealth',
      );
  late final _XRSLAMGetHealth =
      _XRSLAMGetHealthPtr.asFunction<int Function(ffi.Pointer<XRSLAMHealth>)>();

  /// @brief 设置自检阈值。可在 XRSLAMCreate 之前调用;Create/Destroy 不会重置它们。
  /// @param[in] max_abs_cam_imu_delta_sec  |t_cam - t_imu| 的域错配阈值,<= 0 或非有限
  /// 则保持原值。默认 1.0。
  /// @param[in] max_baseline_drift_sec     |delta - baseline| 的告警阈值,同上。默认 0.5。
  /// @param[in] min_landmarks_for_healthy  低于此数且在 TRACKING 中则判 DEGRADED_LOW_TEXTURE,
  /// < 0 则保持原值。默认 20。
  /// @return XRSLAM_OK
  int XRSLAMSetHealthThresholds(
    double max_abs_cam_imu_delta_sec,
    double max_baseline_drift_sec,
    int min_landmarks_for_healthy,
  ) {
    return _XRSLAMSetHealthThresholds(
      max_abs_cam_imu_delta_sec,
      max_baseline_drift_sec,
      min_landmarks_for_healthy,
    );
  }

  late final _XRSLAMSetHealthThresholdsPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Double, ffi.Double, ffi.Int32)>
      >('XRSLAMSetHealthThresholds');
  late final _XRSLAMSetHealthThresholds =
      _XRSLAMSetHealthThresholdsPtr.asFunction<
        int Function(double, double, int)
      >();

  /// @brief 非阻塞拉取最新位姿(条目 06 的 API 形状)。
  ///
  /// 为什么是**拉取**而不是每帧回调:dart:ffi 是同步同线程的。
  /// NativeCallable.isolateLocal 从非创建线程调用会**硬 abort**(不是抛异常),
  /// 而 XRSLAM_ENABLE_THREADING 打开时库内确有真的后台工作线程;
  /// NativeCallable.listener 只支持返回 void 且是异步投递,拿不到同步结果。
  /// 所以正确形状是 Dart 侧自己按需 poll 本函数。
  ///
  /// @param[out] out_pose7     非 NULL,长度 7 的 double 数组。**无条件先清零**。
  /// 布局钉死为 **[qx, qy, qz, qw, px, py, pz]**
  /// —— 四元数在前、实部 w 在**第 4 位**(与 XRSLAMPose
  /// 的 quaternion[4] = {x,y,z,w} 完全一致),平移在后。
  /// 位姿口径 = **body pose**,与 XRSLAMGetBodyPose 同源
  /// (即已乘 imu_to_body)。
  /// @param[out] out_timestamp 非 NULL,秒。**无条件先清零**。
  /// @return XRSLAM_OK           拿到了比上次**更新**、且**几何上合法**的位姿。
  /// XRSLAM_NO_NEW_DATA  没有可用的新位姿。**不阻塞、不等待**。两种情况:
  /// (a) 时间戳不比上次调用交出的更新;
  /// (b) 位姿退化 —— 四元数全零或非有限。跟踪器初始化
  /// 之前 detail.cpp:predict_pose 会 setZero(),而
  /// track_camera 照样连着合法时间戳一起存下来,
  /// 所以"时间戳在前进"**不能**当作位姿可用的判据。
  /// 这两种情况下 out_pose7 保持**全零**、out_timestamp
  /// 保持 0,内部"已交付时间戳"也不前进。
  /// XRSLAM_ERR_BAD_ARG / XRSLAM_ERR_NOT_CREATED / XRSLAM_ERR_INTERNAL
  /// @note 位姿只在 XRSLAMRunOneFrame 里前进(Detail::track_camera 才写 latest_pose_);
  /// 只 push IMU 不调 RunOneFrame,本函数会一直返回 XRSLAM_NO_NEW_DATA。
  /// @note 内部持短锁,可能阻塞在锁上;ffigen/@Native 绑定**不要**标 isLeaf: true。
  int XRSLAMTryGetLatestPose(
    ffi.Pointer<ffi.Double> out_pose7,
    ffi.Pointer<ffi.Double> out_timestamp,
  ) {
    return _XRSLAMTryGetLatestPose(out_pose7, out_timestamp);
  }

  late final _XRSLAMTryGetLatestPosePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Double>, ffi.Pointer<ffi.Double>)
        >
      >('XRSLAMTryGetLatestPose');
  late final _XRSLAMTryGetLatestPose =
      _XRSLAMTryGetLatestPosePtr.asFunction<
        int Function(ffi.Pointer<ffi.Double>, ffi.Pointer<ffi.Double>)
      >();

  /// @brief depth-fusion telemetry from the latest optimization.
  /// @param[out] seeded number of active landmarks carrying a LiDAR depth prior.
  /// @param[out] total  number of active landmarks in the sliding window.
  void XRSLAMGetDepthFusionStats(
    ffi.Pointer<ffi.Int> seeded,
    ffi.Pointer<ffi.Int> total,
  ) {
    return _XRSLAMGetDepthFusionStats(seeded, total);
  }

  late final _XRSLAMGetDepthFusionStatsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Int>, ffi.Pointer<ffi.Int>)
        >
      >('XRSLAMGetDepthFusionStats');
  late final _XRSLAMGetDepthFusionStats =
      _XRSLAMGetDepthFusionStatsPtr.asFunction<
        void Function(ffi.Pointer<ffi.Int>, ffi.Pointer<ffi.Int>)
      >();

  /// @brief destroy SLAM system
  void XRSLAMDestroy() {
    return _XRSLAMDestroy();
  }

  late final _XRSLAMDestroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>('XRSLAMDestroy');
  late final _XRSLAMDestroy = _XRSLAMDestroyPtr.asFunction<void Function()>();
}

/// XRSLAM sensor data
/// /
/// /**
/// @brief input sensor data type
enum XRSLAMSensorType {
  /// !< gray image.
  XRSLAM_SENSOR_CAMERA(0),

  /// !< depth image.
  XRSLAM_SENSOR_DEPTH_CAMERA(1),

  /// !< acceleration.
  XRSLAM_SENSOR_ACCELERATION(2),

  /// !< gyroscope.
  XRSLAM_SENSOR_GYROSCOPE(3),

  /// !< gravity.
  XRSLAM_SENSOR_GRAVITY(4),

  /// !< rotation vector.
  XRSLAM_SENSOR_ROTATION_VECTOR(5),
  XRSLAM_SENSOR_UNKNOWN(6);

  final int value;
  const XRSLAMSensorType(this.value);

  static XRSLAMSensorType fromValue(int value) => switch (value) {
    0 => XRSLAM_SENSOR_CAMERA,
    1 => XRSLAM_SENSOR_DEPTH_CAMERA,
    2 => XRSLAM_SENSOR_ACCELERATION,
    3 => XRSLAM_SENSOR_GYROSCOPE,
    4 => XRSLAM_SENSOR_GRAVITY,
    5 => XRSLAM_SENSOR_ROTATION_VECTOR,
    6 => XRSLAM_SENSOR_UNKNOWN,
    _ => throw ArgumentError('Unknown value for XRSLAMSensorType: $value'),
  };
}

/// @brief Image extension info
final class XRSLAMImageExtension extends ffi.Struct {
  /// !< image exposure time.
  @ffi.Double()
  external double exposure_time;

  /// !< default focus info.
  @ffi.Double()
  external double default_focus_distance;

  /// !< current focal length.
  @ffi.Double()
  external double focal_length;

  /// !< current focus distance.
  @ffi.Double()
  external double focus_distance;
}

/// [pw] ★ 帧时间戳语义契约(条目 09)★
///
/// 背景:两端采集层默认给的**不是同一个东西**,而库内没有任何 td(time offset)
/// 状态量 —— `state.h: ES_SIZE == 15`,误差状态只有 Q/P/V/BG/BA。yaml 里那个
/// `camera_time_offset` 是**死旋钮**:只在 yaml_config.cpp 解析、config.cpp 打印,
/// xrslam/src 里零消费。所以时间戳约定必须由采集层负责对齐,库这一层只做声明、
/// 换算与自检。
/// - Android `SensorTimestamp` / `CaptureResult.SENSOR_TIMESTAMP`:官方文档说明
/// 是**第一行(first row)曝光开始**的时刻。
/// - iOS `CMSampleBufferGetPresentationTimeStamp`:Apple **没有文档化**它指向
/// 曝光窗口的哪一点。不要假设它等于 Android 的语义。
///
/// ★ 本库的规范(canonical)约定 ★
/// XRSLAMImage.timeStamp 一律解释为:
/// **图像几何中心行(center row)的曝光中点(mid-exposure)**,单位秒,
/// 且与 XRSLAMAcceleration.timestamp / XRSLAMGyroscope.timestamp
/// **处在同一个时钟域**(同一 epoch、同一单调时钟)。
/// 选这个点的理由:它是全帧曝光能量的一阶矩,也是 rolling shutter 下"平均像素"
/// 的采样时刻,对纯平移/纯旋转都是无偏的一阶近似。
///
/// 采集层要么自己换算到 canonical 并声明 XRSLAM_TS_CANONICAL,要么如实声明原始
/// 语义 + 填 readout_time,由 PushImage 替你换算。**不声明**(默认 0 =
/// XRSLAM_TS_UNSPECIFIED)时库按原值使用,但会在 XRSLAMHealth 里把
/// `timestamp_convention` 报成 UNSPECIFIED —— 这是"我不知道"的显式记号,不是默认正确。
enum XRSLAMTimestampConvention {
  XRSLAM_TS_UNSPECIFIED(0),
  XRSLAM_TS_CANONICAL(1),
  XRSLAM_TS_FIRST_ROW_EXPOSURE_START(2),
  XRSLAM_TS_FIRST_ROW_EXPOSURE_MID(3);

  final int value;
  const XRSLAMTimestampConvention(this.value);

  static XRSLAMTimestampConvention fromValue(int value) => switch (value) {
    0 => XRSLAM_TS_UNSPECIFIED,
    1 => XRSLAM_TS_CANONICAL,
    2 => XRSLAM_TS_FIRST_ROW_EXPOSURE_START,
    3 => XRSLAM_TS_FIRST_ROW_EXPOSURE_MID,
    _ => throw ArgumentError(
      'Unknown value for XRSLAMTimestampConvention: $value',
    ),
  };
}

/// @brief input gray image data
final class XRSLAMImage extends ffi.Struct {
  /// !< contains the intensity value for each image pixel.
  external ffi.Pointer<ffi.UnsignedChar> data;

  /// !< timestamp in second.
  @ffi.Double()
  external double timeStamp;

  /// !< image stride, number of bytes per row.
  @ffi.Int()
  external int stride;

  /// !< camera id.
  @ffi.Int()
  external int camera_id;

  /// !< image channel.
  @ffi.Int()
  external int channel;

  /// !< ext info of image.
  external ffi.Pointer<XRSLAMImageExtension> ext;

  /// !< 本帧实际宽度(像素)。0 = 未填,回退到 yaml cam0.resolution 并警告一次。
  @ffi.Int()
  external int width;

  /// !< 本帧实际高度(像素)。0 = 未填,回退到 yaml cam0.resolution 并警告一次。
  @ffi.Int()
  external int height;

  @ffi.Double()
  external double readout_time;

  @ffi.Int32()
  external int timestamp_convention;

  @ffi.Int32()
  external int reserved0;
}

/// @brief input depth image data
final class XRSLAMDepthImage extends ffi.Struct {
  /// !< depth in millimetres (0 = invalid), row-major.
  external ffi.Pointer<ffi.Uint16> data;

  /// !< optional per-pixel confidence (may be null).
  external ffi.Pointer<ffi.Uint16> confidence;

  /// !<  timestamp in second.
  @ffi.Double()
  external double timeStamp;

  /// !< depth map width in pixels.
  @ffi.Int()
  external int width;

  /// !< depth map height in pixels.
  @ffi.Int()
  external int height;
}

/// @brief input acceleration data
final class XRSLAMAcceleration extends ffi.Struct {
  /// !< acceleration raw data.
  @ffi.Array.multi([3])
  external ffi.Array<ffi.Double> data;

  /// !< timestamp in second.
  @ffi.Double()
  external double timestamp;
}

/// @brief input gyroscope data
final class XRSLAMGyroscope extends ffi.Struct {
  /// !< gyroscope raw data.
  @ffi.Array.multi([3])
  external ffi.Array<ffi.Double> data;

  /// !< timestamp in second.
  @ffi.Double()
  external double timestamp;
}

/// @brief input gravity direction data
final class XRSLAMGravity extends ffi.Struct {
  /// !< gravity direction.
  @ffi.Array.multi([3])
  external ffi.Array<ffi.Double> data;

  /// !< timestamp in second.
  @ffi.Double()
  external double timestamp;
}

/// @brief attitude of the device
final class XRSLAMRotationVector extends ffi.Struct {
  /// !< attitude of the device.
  @ffi.Array.multi([4])
  external ffi.Array<ffi.Double> data;

  /// !< timestamp in second.
  @ffi.Double()
  external double timestamp;
}

/// XRSLAM tracking result
/// /
/// /**
/// @brief slam result data type
enum XRSLAMResultType {
  /// !< body pose.
  XRSLAM_RESULT_BODY_POSE(0),

  /// !< camera pose.
  XRSLAM_RESULT_CAMERA_POSE(1),

  /// !< system state.
  XRSLAM_RESULT_STATE(2),

  /// !< 3D landmarks.
  XRSLAM_RESULT_LANDMARKS(3),

  /// !< 2D features.
  XRSLAM_RESULT_FEATURES(4),

  /// !< imu bias.
  XRSLAM_RESULT_BIAS(5),

  /// !< [pw] NOT IMPLEMENTED,落到空 break。
  XRSLAM_RESULT_DEBUG_LOGS(6),

  /// !< [pw] 已移除,改用 XRSLAMGetVersion。
  XRSLAM_RESULT_VERSION(7),
  XRSLAM_RESULT_UNKNOWN(8),
  XRSLAM_INFO_INTRINSICS(9);

  final int value;
  const XRSLAMResultType(this.value);

  static XRSLAMResultType fromValue(int value) => switch (value) {
    0 => XRSLAM_RESULT_BODY_POSE,
    1 => XRSLAM_RESULT_CAMERA_POSE,
    2 => XRSLAM_RESULT_STATE,
    3 => XRSLAM_RESULT_LANDMARKS,
    4 => XRSLAM_RESULT_FEATURES,
    5 => XRSLAM_RESULT_BIAS,
    6 => XRSLAM_RESULT_DEBUG_LOGS,
    7 => XRSLAM_RESULT_VERSION,
    8 => XRSLAM_RESULT_UNKNOWN,
    9 => XRSLAM_INFO_INTRINSICS,
    _ => throw ArgumentError('Unknown value for XRSLAMResultType: $value'),
  };
}

/// @brief    slam pose.
/// @details  For a 3D point in world coordinate \f$ X_w \f$, its 3D
/// coordinate in the camera frame \f$ X_c = R * X_w + T \f$
final class XRSLAMPose extends ffi.Struct {
  /// !< quaternion of rotation: format [x, y, z, w].
  @ffi.Array.multi([4])
  external ffi.Array<ffi.Double> quaternion;

  /// !< translation vector T.
  @ffi.Array.multi([3])
  external ffi.Array<ffi.Double> translation;

  /// !< timestamp.
  @ffi.Double()
  external double timestamp;
}

final class XRSLAMIntrinsics extends ffi.Struct {
  @ffi.Double()
  external double fx;

  @ffi.Double()
  external double fy;

  @ffi.Double()
  external double cx;

  @ffi.Double()
  external double cy;
}

/// @brief    slam state.
/// @details  SLAM state to show the system status.
enum XRSLAMState {
  /// !< SLAM is in initialize state.
  XRSLAM_STATE_INITIALIZING(0),

  /// !< tracking, success.
  XRSLAM_STATE_TRACKING_SUCCESS(1),

  /// !< tracking, fail.
  XRSLAM_STATE_TRACKING_FAIL(2);

  final int value;
  const XRSLAMState(this.value);

  static XRSLAMState fromValue(int value) => switch (value) {
    0 => XRSLAM_STATE_INITIALIZING,
    1 => XRSLAM_STATE_TRACKING_SUCCESS,
    2 => XRSLAM_STATE_TRACKING_FAIL,
    _ => throw ArgumentError('Unknown value for XRSLAMState: $value'),
  };
}

/// @brief  landmark 3d position.
/// @details x, y, z is world position of the point.
final class XRSLAMLandmark extends ffi.Struct {
  @ffi.Double()
  external double x;

  @ffi.Double()
  external double y;

  @ffi.Double()
  external double z;
}

/// @brief  2d corner in image coordinate.
final class XRSLAMFeature extends ffi.Struct {
  @ffi.Double()
  external double x;

  @ffi.Double()
  external double y;
}

final class XRSLAMFeatures extends ffi.Struct {
  external ffi.Pointer<XRSLAMFeature> features;

  @ffi.Int()
  external int num_features;
}

/// @brief IMU bias.
final class XRSLAMBias extends ffi.Struct {
  @ffi.Array.multi([3])
  external ffi.Array<ffi.Double> data;
}

final class XRSLAMIMUBias extends ffi.Struct {
  external XRSLAMBias acc_bias;

  external XRSLAMBias gyr_bias;
}

/// [pw] ★ 健康状态机(条目 16)★
///
/// "不崩溃"不等于"没坏掉"。本库有两条**静默退化**路径,错误码一条都盖不住:
/// (1) t_cam 与 t_imu 不在同一时钟域时,detail.cpp 的归并条件恒假 ⇒
/// Frame::preintegration.data 为空 ⇒ PreIntegrator::integrate 直接 return
/// false ⇒ 求解器里**一个 IMU 因子都没有**,系统退化成纯单目 SfM,
/// 却照常返回 XRSLAM_STATE_TRACKING_SUCCESS。
/// (2) landmark 发布循环只判 TT_VALID,而未三角化的 track 会带着
/// inv_depth = 0(=> ±Inf)或 -1.0(=> 相机背后的有限垃圾点)被发布。
/// XRSLAMHealth 就是把这两件事(以及时间戳自检的计数)变成**可读数字**。
///
/// 约束:
/// - 纯 C 可编译;字段只追加、不重排、不删除;sizeof 由 static_assert 钉住。
/// - 出参无条件先清零(GetHealth 的第一件事就是 memset)。
/// - 一律 int32_t / int64_t / double,不用 int(ffigen 在 32/64 位上会漂)。
enum XRSLAMHealthState {
  /// !< 未 Create / 已 Destroy。
  XRSLAM_HEALTH_NOT_CREATED(0),
  XRSLAM_HEALTH_HEALTHY(1),

  /// !< 检出上述 (1):IMU 因子为零 / 域错配。
  XRSLAM_HEALTH_DEGRADED_NO_IMU(2),

  /// !< 在跟踪,但可用 landmark 数低于阈值。
  XRSLAM_HEALTH_DEGRADED_LOW_TEXTURE(3),

  /// !< SLAM 自报 TRACKING_FAIL。
  XRSLAM_HEALTH_LOST(4);

  final int value;
  const XRSLAMHealthState(this.value);

  static XRSLAMHealthState fromValue(int value) => switch (value) {
    0 => XRSLAM_HEALTH_NOT_CREATED,
    1 => XRSLAM_HEALTH_HEALTHY,
    2 => XRSLAM_HEALTH_DEGRADED_NO_IMU,
    3 => XRSLAM_HEALTH_DEGRADED_LOW_TEXTURE,
    4 => XRSLAM_HEALTH_LOST,
    _ => throw ArgumentError('Unknown value for XRSLAMHealthState: $value'),
  };
}

final class XRSLAMHealth extends ffi.Struct {
  /// !< 最近一次**被接受**的图像时间戳(已按 convention 换算)。
  @ffi.Double()
  external double last_image_timestamp;

  /// !< 最近一次被接受的 IMU 时间戳(acc 与 gyro 取较新者)。
  @ffi.Double()
  external double last_imu_timestamp;

  /// !< last_image_timestamp - last_imu_timestamp。
  @ffi.Double()
  external double last_cam_imu_delta;

  /// !< 两路都到齐的**第一时刻**记下的差值,作基线。
  @ffi.Double()
  external double baseline_cam_imu_delta;

  /// !< |delta| 的历史最大值。
  @ffi.Double()
  external double max_abs_cam_imu_delta;

  /// !< 当前生效的域错配阈值,默认 1.0 s。
  @ffi.Double()
  external double cam_imu_delta_threshold;

  /// !< |delta - baseline| 的告警阈值,默认 0.5 s。
  @ffi.Double()
  external double baseline_drift_threshold;

  /// !< |delta - baseline| 的历史最大值。
  @ffi.Double()
  external double max_abs_baseline_drift;

  /// !< 最近一次 XRSLAMRunOneFrame 的墙钟耗时(毫秒)。
  @ffi.Double()
  external double last_frame_ms;

  @ffi.Int64()
  external int image_accepted;

  @ffi.Int64()
  external int image_rejected;

  @ffi.Int64()
  external int accel_accepted;

  @ffi.Int64()
  external int accel_rejected;

  @ffi.Int64()
  external int gyro_accepted;

  @ffi.Int64()
  external int gyro_rejected;

  /// !< 按原因分桶(三路合计):时间戳 NaN/Inf。
  @ffi.Int64()
  external int reject_non_finite_ts;

  /// !< 该路时间戳未严格递增(t <= 上一个)。
  @ffi.Int64()
  external int reject_non_monotonic_ts;

  /// !< 其余参数非法(空指针 / 尺寸 / stride / channel)。
  @ffi.Int64()
  external int reject_bad_arg;

  /// !< |t_cam - t_imu| 超阈值的次数。**不拒样本**,只计数。
  @ffi.Int64()
  external int domain_mismatch_events;

  /// !< |delta - baseline| 超阈值的次数。
  @ffi.Int64()
  external int baseline_drift_events;

  /// !< XRSLAMRunOneFrame 实际跑起来的帧数。
  @ffi.Int64()
  external int frames_run;

  /// !< 归并窗口内 IMU 样本数为 0 的帧数(见下)。
  @ffi.Int64()
  external int frames_with_zero_imu;

  /// !< 影子队列溢出丢弃数;>0 本身就是域错配的强信号。
  @ffi.Int64()
  external int shadow_overflow_drops;

  /// !< XRSLAMHealthState。
  @ffi.Int32()
  external int overall;

  /// !< XRSLAMState(未创建时为 TRACKING_FAIL)。 */
  /// /*!< 最近一帧被归并进 preintegration 的 IMU 样本数 —— **C API 层的影子模型**。
  /// XRSLAMManager 用一对影子队列复刻了 detail.cpp track_imu 的归并谓词
  /// (imu.t <= frame.t 则入帧,否则派发该帧)。
  /// ⚠️ 影子模型只吃**加速度计**样本,而 detail.cpp 里一个加速度样本要么立刻
  /// 经插值进 track_imu、要么先缓存到下一枚陀螺到达时才进,还有一类
  /// (陀螺缓冲为空 / 早于最老陀螺)会被**整个丢弃**。所以本字段是"应该有几个"
  /// 的上界估计,与真值同相位但不逐帧相等。
  /// ★ 判"这一帧到底有没有用上 IMU"请优先看 `core_imu_samples`(核内直读)。
  /// 本字段的价值在于:它在**图像/IMU 根本没进核**(时间戳被闸拒、域错配导致
  /// 归并谓词恒假)时依然有数,而核内计数器那时压根不会被更新。
  /// 0 = 影子模型认为这一帧一个 IMU 因子都没有;-1 = 还没有帧被派发过。
  @ffi.Int32()
  external int slam_state;

  @ffi.Int32()
  external int imu_samples_last_frame;

  /// !< 发布循环里 TT_VALID 的总数。
  @ffi.Int32()
  external int landmarks_published;

  /// !< 三分量 isfinite **且** triangulated 的数量。
  @ffi.Int32()
  external int landmarks_usable;

  /// !< 因 ±Inf/NaN 被丢弃(inv_depth==0 除零)。
  @ffi.Int32()
  external int landmarks_rejected_non_finite;

  /// !< 有限但未三角化(inv_depth==-1,相机背后)。
  @ffi.Int32()
  external int landmarks_rejected_untriangulated;

  /// !< 最近一帧声明的 XRSLAMTimestampConvention。
  @ffi.Int32()
  external int timestamp_convention;

  /// !< 0/1:当前 |t_cam - t_imu| 是否仍超阈值。
  @ffi.Int32()
  external int domain_mismatch_active;

  /// !< 0/1:XRSLAM_ENABLE_DEBUG_INSPECTION 是否被关掉。
  @ffi.Int32()
  external int inspection_compiled_out;

  /// !< 0/1:XRSLAM_ENABLE_THREADING(有真后台线程)。 */
  /// /*!< 0/1:inspection 的 bg/ba 槽位是否真的有人写过。
  /// ⚠️ 实测:全仓**没有任何一处**写 sliding_window_current_bg /
  /// sliding_window_current_ba,所以在当前 xrslam/src 下这一位恒为 0,
  /// XRSLAMGetBias 永远返回全零而 rc == XRSLAM_OK。别把那个零当成"偏置很小"。
  @ffi.Int32()
  external int threading_enabled;

  @ffi.Int32()
  external int bias_channel_populated;

  /// !< 核内最近一帧的图像时间戳(秒)。
  @ffi.Double()
  external double core_frame_timestamp;

  /// !< 每到达一帧 +1。**两次读到同一个值 = 期间没有新帧
  /// 走到跟踪器**,是"核卡住了"最直接的判据;
  /// 0 = 从来没有帧到达过。
  @ffi.Int64()
  external int core_frame_seq;

  /// !< 累计出现 core_imu_samples == 0 的帧数。 */
  /// /*!< ★ 判"静默退化成纯单目"就看这个 ★ 该帧**真实** IMU 样本数(补桩之前)。
  /// 0 = 这一帧一个惯性观测都没有;-1 = 还没有任何帧到达跟踪器。
  @ffi.Int64()
  external int core_imu_starved_frames;

  @ffi.Int32()
  external int core_imu_samples;

  @ffi.Int32()
  external int core_imu_samples_integrated;

  /// !< 该帧检出后的关键点总数(含跟踪继承)。-1 = 未知。
  @ffi.Int32()
  external int detected_keypoints;

  /// !< 从上一帧成功传递过来的关键点数(LK + 本质矩阵 + 泊松盘之后)。
  @ffi.Int32()
  external int tracked_keypoints;

  /// !< LK 存活里通过本质矩阵几何校验的内点数。
  @ffi.Int32()
  external int inlier_keypoints;

  /// !< 滑窗最新帧看到的 VALID&TRIANGULATED&STATIC 轨迹数;
  /// -1 = 后端还没跑起来。 */
  /// /*!< 0/1:核内遥测这次到底读到没有。0 = 还没有任何帧走到 feature_tracker
  /// (core_frame_seq == 0 且 core_imu_samples == -1),此时上面 core_* 全是初值,
  /// 不要**据此判 DEGRADED_NO_IMU。
  @ffi.Int32()
  external int mapped_landmarks;

  @ffi.Int32()
  external int core_health_available;

  @ffi.Int32()
  external int latest_pose_degenerate;
}

/// @brief landmark 过滤计账。被丢掉的点必须能被数出来,否则又是一次静默失效。
final class XRSLAMLandmarkStats extends ffi.Struct {
  /// !< 发布循环里 TT_VALID 的总数(过滤前)。
  @ffi.Int32()
  external int published;

  /// !< 三分量任一 NaN/±Inf 而被丢弃。
  @ffi.Int32()
  external int rejected_non_finite;

  /// !< 有限但 triangulated == false。
  @ffi.Int32()
  external int rejected_untriangulated;

  /// !< 实际写进 out_xyz 的点数(受容量截断)。
  @ffi.Int32()
  external int returned;
}
